DROP DATABASE SistemiBot;
CREATE DATABASE SistemiBot;
USE SistemiBot;

CREATE TABLE Polls (
  PollID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Answers INT DEFAULT 0,
  Average DOUBLE DEFAULT 0,
  PRIMARY KEY(PollID)
);

CREATE TABLE Answers (
  AnswerID INT NOT NULL AUTO_INCREMENT,
  UserChatID BIGINT NOT NULL,
  PollName VARCHAR(50) NOT NULL,
  Answer INT NOT NULL,
  PRIMARY KEY(AnswerID)
);